name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  cloud_firestore: ^3.4.8

  # Network
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  retrofit: '>=3.0.0 <4.0.0'
  logger: any  #for logging purpose

  # dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  equatable: ^2.0.3

  # localization
  flutter_localizations:
    sdk: flutter

  # bloc
  flutter_bloc: ^8.0.1

  logging: ^1.0.2
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  go_router: ^4.0.0
  flutter_svg: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  country_code_picker: ^2.0.2
  phone_number: ^0.12.0+2
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator:

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'

flutter_intl:
  enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - config/app_config.json
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
